BOT_TOKEN = '5961464439:AAEE7MimMqkW8WYXoXecUwelTBXAvaSSeiY'
ASSETS = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'DOGEUSDT', 'EURGBP', 'EURUSD', 'GBPUSD']

TOKEN = 'MTA3NDcxODE4NzQyNzQ3NTU2Ng.GU-dVr.4kI0sCK9Acfj8Iw4YKRmTwUuimApd5kjsfcCVQ'